# import tkinter as tk
# def update_label():
#     name = entry.get()
#     label.config(text = f"Hello,{name}")

# root = tk.Tk()
# root.title("Hello GUI")
# root.geometry("300x200")

# label = tk.Label(root,text="Ente your name:")
# label.pack(pady=10)

# entry = tk.Entry(root)
# entry.pack(pady = 5)

# button = tk.Button(root,text="Click Me",command=update_label)
# button.pack(pady=10)
# root.mainloop()

